### ISSUE TITLE
[канал]:

### ISSUE THREAD

**Issue by ithofet** [ityoutubers/ityoutubers.com#11]
### Ссылка на канал

https://www.youtube.com/@S0ERDEVS

### Название канала

 S0ER 

### Описание канала со странице О канале

███─████─███─████
█───█──█─█───█──█
███─█──█─███─████
──█─█──█─█───█─█
███─████─███─█─█

███████████▓░░░ 78%
* SOER - это сокращение от SOftware EngineeR

👉👉👉 Основное место общения и публикации новых видео - https://t.me/softwareengineervlog

Канал для разработчиков программного обеспечения, инженеров и всех кому интересно разобраться в программировании глубже, а так же расширить кругозор в области АйТи.

Формула канала - это баланс между следующими темами:

🔥 советы как лучше развиваться и стать отличным программистом
🔥 обзор книг для айтишников
🔥 сборка софта и работа с чужими исходниками
🔥 обзор исходников на github
🔥 архитектура программного обеспечения
🔥 теория программирования 
🔥 пет-проекты и OpenSource ❤️
🔥 хобби для развития кругозора ⚙️

Как найти в сети?

👉 SoundCloud - https://soundcloud.com/software-engineer-vlog/
👉  Дополнительный платный материал по архитектуре и программированию - https://soer.pro

Мерч канала
👉 https://s0er.printdirect.ru/

**Comment by nLight** [comment]
в сообществе
