### ISSUE TITLE
[канал]: Data Science

### ISSUE THREAD

**Issue by jusat** [ityoutubers/ityoutubers.com#16]
### Ссылка на канал

https://www.youtube.com/@GlebMikhaylov

### Название канала

 Глеб Михайлов

### Описание канала со странице О канале

Всем привет! Я Глеб Михайлов. Я занимаюсь анализом данных с 2011 года и преподаю с 2018. Я работал аналитиком и дата саентистом в Альфе, Сбере, Ростелекоме. C 2019 работаю наставником в Яндекс.Практикуме, веду вебинары по анализу данных и data science. У меня также есть курсы на Udemy и Stepik (ищи в ссылках канала).

В анализе данных и дата саенс я абсолютный самоучка – учился по курсам на Udemy, Coursera, Stepik и т.д. Читал книги, смотрел YouTube. Я знаю каково это осваивать новую профессию самому, и поэтому, я учу максимально просто, без заумствований и делюсь своими практическими наработками и лайфхаками.

**Comment by nLight** [comment]
👍
