### ISSUE TITLE
[канал]: Data Science

### ISSUE THREAD

**Issue by jusat** [ityoutubers/ityoutubers.com#17]
### Ссылка на канал

https://www.youtube.com/@karpovcourses/

### Название канала

karpov.courses

### Описание канала со странице О канале

Всем привет! Мы – команда karpov.courses.
Мы делаем крутую Data Science школу и бесплатно делимся полезными знаниями по аналитике, статистике и машинному обучению. В этом канале мы публикуем записи своих вебинаров, интервью с IT-специалистами в сфере Data Science и другие интересные видео :)

**Comment by nLight** [comment]
👍
