### ISSUE TITLE
[канал]: 

### ISSUE THREAD

**Issue by mufdvr** [ityoutubers/ityoutubers.com#22]
### Ссылка на канал

https://www.youtube.com/@GNULinuxPro/

### Название канала

GNU Linux Pro

### Описание канала со странице О канале

Про GNU/Linux и IT

Вопросы и ответы: https://faqabout.me/iam/gnu-linux-pro

Сайт: https://gnulinux.pro/
Телеграм: https://t.me/gnuslashlinux

**Comment by nLight** [comment]
👍
