### ISSUE TITLE
[канал]: 

### ISSUE THREAD

**Issue by krot0glot** [ityoutubers/ityoutubers.com#26]
### Ссылка на канал

https://youtube.com/@beginend95

### Название канала

Begin End

### Описание канала со странице О канале

Здесь можно научиться программировать на языке Си и С++ с абсолютного нуля. Кроме того мы изучаем графический движок OpenGl с еще большего нуля. Я подробно объясняю материал шаг за шагом. Кроме того мы будем периодически делать простые, но интересные игры на каждом изученном языке.

**Comment by nLight** [comment]
👍
