### ISSUE TITLE
[канал]: 

### ISSUE THREAD

**Issue by odinsacred** [ityoutubers/ityoutubers.com#28]
### Ссылка на канал

https://www.youtube.com/@selfedu_rus

### Название канала

selfedu

### Описание канала со странице О канале

Видеоуроки по математике, алгоритмам обработки данных (в том числе по нейронным сетям), по языкам программирования: С, С++, Java, Python (Питон), JavaScript, HTML, CSS, а также по их многочисленным библиотекам.

**Comment by nLight** [comment]
👍
