### ISSUE TITLE
[канал]: VladimirMedintsev

### ISSUE THREAD

**Issue by odinsacred** [ityoutubers/ityoutubers.com#29]
### Ссылка на канал

https://www.youtube.com/@VladimirMedintsev

### Название канала

VladimirMedintsev

### Описание канала со странице О канале

Channel about technology, electronics and design.
This is my personal blog as an engineer and developer. In the commercials, I set out my personal, sometimes very subjective opinion, which in any case is not the ultimate truth. I beg you not to take these videos as a teaching material.

**Comment by nLight** [comment]
👍
