### ISSUE TITLE
[канал]: Johannes 4GNU_Linux

### ISSUE THREAD

**Issue by odinsacred** [ityoutubers/ityoutubers.com#30]
### Ссылка на канал

https://www.youtube.com/@johannes4gnu_linux96

### Название канала

Johannes 4GNU_Linux

### Описание канала со странице О канале

Here on my Channel I put out some videos about GNU/Linux with a focus on applications for automation and Embedded Systems. But here are also some videos about some useful tools you can use on GNU/Linux.

**Comment by nLight** [comment]
👍
