### ISSUE TITLE
[канал]: Kofybrek

### ISSUE THREAD

**Issue by odinsacred** [ityoutubers/ityoutubers.com#31]
### Ссылка на канал

https://www.youtube.com/@Kofybrek

### Название канала

Kofybrek

### Описание канала со странице О канале

This channel is about having fun with programming!

Here you'll find cool algorithm visualizations, game development, working with artificial intelligence and machine learning, etc.

I use C++ most of the time because it's my favorite (and also the only programming language I know).

**Comment by nLight** [comment]
👍
