### ISSUE TITLE
[канал]: NR.electronics

### ISSUE THREAD

**Issue by odinsacred** [ityoutubers/ityoutubers.com#32]
### Ссылка на канал

https://www.youtube.com/@NRelectronics

### Название канала

NR.electronics

### Описание канала со странице О канале

The channel for both beginners and professionals in the field of electronics, programming MCU STM32, Renesas, Milandr. The channel also presents a large and detailed course on programming in the C language (C11 / C18), taking into account the MISRA C programming rules, CERT coding standards, as well as a separate video series on MISRA C.

**Comment by nLight** [comment]
👍
