### ISSUE TITLE
[канал]: Doubletapp

### ISSUE THREAD

**Issue by nichuse** [ityoutubers/ityoutubers.com#35]
### Ссылка на канал

https://www.youtube.com/@doubletapp9440

### Название канала

Doubletapp

### Описание канала со странице О канале

Канал компании Doubletapp.

Мы создаем цифровые продукты полного цикла. На канале публикуем образовательные ролики для IT-специалистов, делаем обзоры на технику, делимся фрагментами с мероприятий из мира IT.

**Comment by nLight** [comment]
👍
