### ISSUE TITLE
[канал]: АйТи Синяк

### ISSUE THREAD

**Issue by AndrewSorokin540** [ityoutubers/ityoutubers.com#36]
### Ссылка на канал

https://www.youtube.com/@it-sin9k/featured

### Название канала

АйТи Синяк

### Описание канала со странице О канале

Описание
Всем привет! 

Я Фронтенд разработчик со стажем более 7-ми лет в HTML, CSS и JS. Защитил магистерскую на тему "Доступности интерфейсов для людей с ограниченными возможностями". У меня опыт в самых разных областях: социальные сети, бухгалтерский учет, недвижимость и мессенджер наподобие Телеграм. Технические требования к этим проектам самые разные: адаптивность, сокеты, кэширование сервис воркерами, бесконечные пуш уведомления и даже переиспользуемость кода между Веб версией и React Native. 

Все эти задачи можно решать по-разному, и я хочу поделиться своим личным набором лучших практик. Надеюсь, что каждый сможет почерпнуть что-то новое и полезное для себя, а также это вдохновит других разработчиков поделиться своими знаниями на этом канале.  

И самое главное, пишите комменты если вы с чем-то не согласны или вы знаете вариант лучше, ведь только в обсуждении рождается истина! 

А пока наслаждайтесь нашим культовым плейлистом трюков с react-router

**Comment by nLight** [comment]
👍
