### ISSUE TITLE
[канал]: PurpleSchool | Anton Larichev

### ISSUE THREAD

**Issue by AndrewSorokin540** [ityoutubers/ityoutubers.com#38]
### Ссылка на канал

https://www.youtube.com/@PurpleSchool

### Название канала

PurpleSchool | Anton Larichev

### Описание канала со странице О канале

Канал о разработке и обучающие видео по JavaScript, TypeScript, Node.js, React, Angular, NestJS, Next.js, Docker и многим другим технологиям.

Я работаю техническим директором в компании по продаже и оценке автомобилей с пробегом. Занимаюсь разработкой уже более 12 лет и имею большой опыт: JavaScript, TypeScript, Php, Go, C#, Swift и Python. Активно внедряю гибкие методологии разработки в компании и внутренние обучения для команд.

**Comment by nLight** [comment]
👍
