### ISSUE TITLE
[канал]: Слёрм

### ISSUE THREAD

**Issue by ginkoru** [ityoutubers/ityoutubers.com#40]
### Ссылка на канал

https://www.youtube.com/channel/UCK5MedKoNJ5aRahfGOIGx6g

### Название канала

Слёрм

### Описание канала со странице О канале

Слёрм — образовательный канал для инженеров и технических лидеров: Kubernetes, DevOps, Docker, CI/CD, Ceph, SRE и многое другое. Также Слёрм-  это Учебный центр.

**Comment by nLight** [comment]
👍
