### ISSUE TITLE
[канал]: Диджитализируй!

### ISSUE THREAD

**Issue by shwartin** [ityoutubers/ityoutubers.com#47]
### Ссылка на канал

https://www.youtube.com/@t0digital

### Название канала

Диджитализируй!

### Описание канала со странице О канале

Сказать каналу спасибо и получить доступ к эксклюзивным выпускам — https://boosty.to/digitalize.team

Наш VK: https://vk.com/digitalize.team

Наши проекты:
* digitalize.team — Диджитализируй! делает сложные информационные системы для бизнеса
* salesbeat.pro — модуль доставки для интернет-магазинов, каким он должен быть

**Comment by nLight** [comment]
уже на сайте
