### ISSUE TITLE
[канал]:

### ISSUE THREAD

**Issue by raymoff** [ityoutubers/ityoutubers.com#52]
### Ссылка на канал

https://www.youtube.com/@IlyaBodrovKrukowski

### Название канала

 Ilya Krukowski

### Описание канала со странице О канале

Илья Круковский. Обучающие видео о разработке программного обеспечения (Ruby/Rails, Solidity/Ethereum, JavaScript, Elixir и не только): никакой воды, только конкретика.

**Comment by nLight** [comment]
👍
