### ISSUE TITLE
[канал]: Немного IT

### ISSUE THREAD

**Issue by gosolivs** [ityoutubers/ityoutubers.com#63]
### Ссылка на канал

https://youtube.com/@someit

### Название канала

Немного IT

### Описание канала со странице О канале

Идея подкаста родилась из «виртуальных разговоров у кулера». Наша команда полностью распределенная, нередко рабочие созвоны затягиваются и переходят в дискуссии. Мы очень разнопланово развиты в IT, у каждого свой бекграунд, экспертиза и разные проекты за плечами. В какой-то момент мы решили, что наши обсуждения, а иногда и споры могут быть интересны и более широкому кругу разработчиков. Так и родился канал «Немного  IT».

**Comment by nLight** [comment]
👍
