### ISSUE TITLE
[канал]: webDev

### ISSUE THREAD

**Issue by YauhenKavalchuk** [ityoutubers/ityoutubers.com#64]
### Ссылка на канал

https://www.youtube.com/channel/UCE9ODjNIkOHrnSdkYWLfYhg

### Название канала

webDev

### Описание канала со странице О канале

webDev - образовательный канал о веб-разработке. Здесь вы найдёте курсы по: HTML, CSS, JavaScript, React, VueJS, Node.js, TypeScript, GraphQL, NextJS, MongoDB, Redux, Redux-Saga, Jest, Enzyme, React Testing Library, CSS Grid, Flexbox...

**Comment by nLight** [comment]
👍
