### ISSUE TITLE
[канал]: 

### ISSUE THREAD

**Issue by romanchechyotkin** [ityoutubers/ityoutubers.com#8]
### Ссылка на канал

https://www.youtube.com/@UlbiTV

### Название канала

Ulbi TV

### Описание канала со странице О канале

Привет друзья!) Меня зовут Ульби Тимур. Я fullstack разработчик)
На моем канале будут размещаться видео уроки посвященные программированию, здесь вы найдете много полезного по разным темам, javascript, backend, frontend, базы данных, алгоритмы и многое другое!)

Telegram канал для общения - https://t.me/ulbi_tv

Поддержать меня и мой канал вы можете по ссылкам ниже.

Patreon/boosty - https://boosty.to/ulbitv

Qiwi кошелек - http://qiwi.com/n/BODYE821​
Яндекс деньги - https://yoomoney.ru/to/4100116193037469

**Comment by nLight** [comment]
В сообществе
