### ISSUE TITLE
[канал]: PythonToday

### ISSUE THREAD

**Issue by Vorobey-AV** [ityoutubers/ityoutubers.com#9]
### Ссылка на канал

https://www.youtube.com/@PythonToday/

### Название канала

PythonToday

### Описание канала со странице О канале

Привет!

Освой одну их самых топовых профессий в мире, начни работать в удовольствие из любой точки планеты!
На канале [PYTHON:TODAY] ты найдешь видео и текстовые трансляции уроков:

✔️ По созданию ботов
✔️ Приложений на смартфон
✔️ Шифрованию
✔️ Парсингу сайтов
✔️ Машинному обучению и big data с нуля

**Comment by nLight** [comment]
добавил, появится в следующем обновлении
